// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import CommentCounterController from "./comment_counter_controller"
application.register("comment-counter", CommentCounterController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import ShoutboxController from "./shoutbox_controller"
application.register("shoutbox", ShoutboxController)

import SidebarController from "./sidebar_controller"
application.register("sidebar", SidebarController)

import TestController from "./test_controller"
application.register("test", TestController)

import SettingsTabController from "./settings_tab_controller"
application.register("settings-tab", SettingsTabController)
